constexpr int MEM_SIZE = 262144;        // bytes
constexpr int CACHE_SIZE = 2048;        // bytes
constexpr int CACHE_LINE_SIZE = 64;     // bytes
constexpr int CACHE_LINE_COUNT = 32;
constexpr int CACHE_WAY = 4;
constexpr int CACHE_SETS = 8;
constexpr int ADDR_LEN = 18;            // bits
constexpr int CACHE_TAG_LEN = 9;        // bits
constexpr int CACHE_INDEX_LEN = 3;      // bits
constexpr int CACHE_OFFSET_LEN = 6;     // bits
